### ISSUE TITLE
ModuleNotFoundError: No module named 'mahjong_utils'

### ISSUE THREAD

**Issue by a930389426** [bot-ssttkkl/nonebot-plugin-mahjong-utils#10]
![~K9M~9 AJJJ@%@2DAIA(BN4](https://github.com/ssttkkl/nonebot-plugin-mahjong-utils/assets/59648220/45bd16a9-abee-4b64-835b-0d5018c8b80c)

**Comment by ssttkkl** [comment]
pip install mahjong-utils

**Comment by a930389426** [comment]
![image](https://github.com/ssttkkl/nonebot-plugin-mahjong-utils/assets/59648220/29d4f944-aaae-4b82-94d3-52707bb885e4)

**Comment by a930389426** [comment]
> pip install mahjong-utils
变成nonebot_plugin_mahjong_utils了

**Comment by ssttkkl** [comment]
我看你是直接把源码拷贝过去了？那就不要把目录名改了，目录名就是nonebot_plugin_mahjong_utils，改了以后找不到模块了

**Comment by a930389426** [comment]
![image](https://github.com/ssttkkl/nonebot-plugin-mahjong-utils/assets/59648220/f366594e-88b0-46a9-b50c-69f528550bf0)
我这目录名就是这个

**Comment by a930389426** [comment]
![image](https://github.com/ssttkkl/nonebot-plugin-mahjong-utils/assets/59648220/da6d11ad-f3fc-473e-9ec1-c31d3ed7ce41)
打开后就是这样的

**Comment by ssttkkl** [comment]
还有问题那我不知道了，推荐你通过pip安装的方式安装插件

**Comment by ssttkkl** [comment]
pip install nonebot-plugin-mahjong-utils

然后你用zhenxun的话，修改bot.py，在`nonebot.load_plugins("extensive_plugin")`后边加上一行`nonebot.load_plugin("nonebot_plugin_mahjong_utils")`
