### ISSUE TITLE
有几个疑问

### ISSUE THREAD

**Issue by sapphire159** [bot-ssttkkl/nonebot-plugin-mahjong-utils#14]
使用前我有几个疑问想问下，
1、这个字牌怎么输入
2、我看介绍里，分析并没有加前缀，那是否每句话都会进分析程序呢，还是有什么识别，加一个分析前缀会不会好些呢。毕竟是要和其它插件混用的。
谢谢

**Comment by ssttkkl** [comment]
> 1、这个字牌怎么输入

1z2z3z4z5z6z7z，对应东南西北白发中

> 2、我看介绍里，分析并没有加前缀，那是否每句话都会进分析程序呢，还是有什么识别，加一个分析前缀会不会好些呢。毕竟是要和其它插件混用的。

没有前缀，正则fullmatch到符合格式的、并且牌枚数大于4张的才会计算。其他插件应该也不会响应114514p1919s810m这种消息吧（

**Comment by sapphire159** [comment]
了解了，感谢
