### ISSUE TITLE
有个使用上的问题

### ISSUE THREAD

**Issue by sapphire159** [bot-ssttkkl/nonebot-plugin-mahjong-utils#15]
请问
白白 （暗刻）东东东东南南南南西西西西北北北北 怎么输入？
我尝试55z 0110022003300440z 报错

然后”手牌代码后可通过空格分割输入副露、自风、场风、dora、额外役。“这句如何理解，是否理解为按上述顺序输入。自场风输入什么，额外役如何输入。

**Comment by ssttkkl** [comment]
输入示例：55z 0110z 0220z 0330z 0440z 自风东 场风西 dora18 立直 一发 自摸

除去第一段手牌代码以外，其他段可按照任意顺序输入
________________________________
发件人: sapphire159 ***@***.***>
发送时间: 2023年12月11日 23:48
收件人: bot-ssttkkl/nonebot-plugin-mahjong-utils ***@***.***>
抄送: Subscribed ***@***.***>
主题: [bot-ssttkkl/nonebot-plugin-mahjong-utils] 有个使用上的问题 (Issue #15)


请问
白白 （暗刻）东东东东南南南南西西西西北北北北 怎么输入？
我尝试55z 0110022003300440z 报错

然后”手牌代码后可通过空格分割输入副露、自风、场风、dora、额外役。“这句如何理解，是否理解为按上述顺序输入。自场风输入什么，额外役如何输入。

―

**Comment by sapphire159** [comment]
5z3z 1111m 1111z 333z 444z 计算进张时右边的不识别为副露，感觉有些影响

**Comment by ssttkkl** [comment]
进张也不用考虑副露啊，只有算和牌的时候会用到后面跟的其他东西

________________________________
发件人: sapphire159 ***@***.***>
发送时间: 2023年12月12日 0:00
收件人: bot-ssttkkl/nonebot-plugin-mahjong-utils ***@***.***>
抄送: ssttkkl ***@***.***>; Comment ***@***.***>
主题: Re: [bot-ssttkkl/nonebot-plugin-mahjong-utils] 有个使用上的问题 (Issue #15)


5z3z 1111m 1111z 333z 444z 计算进张时右边的不识别为副露，感觉有些影响

―

**Comment by ssttkkl** [comment]
对哦理论上副露能提供一丢丢余量相关的信息，但是不太实用就没做（
________________________________
发件人: 黄 文龙 ***@***.***>
发送时间: 2023年12月12日 0:00
收件人: bot-ssttkkl/nonebot-plugin-mahjong-utils ***@***.***>
主题: 回复: [bot-ssttkkl/nonebot-plugin-mahjong-utils] 有个使用上的问题 (Issue #15)

进张也不用考虑副露啊，只有算和牌的时候会用到后面跟的其他东西

________________________________
发件人: sapphire159 ***@***.***>
发送时间: 2023年12月12日 0:00
收件人: bot-ssttkkl/nonebot-plugin-mahjong-utils ***@***.***>
抄送: ssttkkl ***@***.***>; Comment ***@***.***>
主题: Re: [bot-ssttkkl/nonebot-plugin-mahjong-utils] 有个使用上的问题 (Issue #15)


5z3z 1111m 1111z 333z 444z 计算进张时右边的不识别为副露，感觉有些影响

―
