### ISSUE TITLE
回复的指令会循环触发机器人，导致刷屏。

### ISSUE THREAD

**Issue by nqwu** [bot-ssttkkl/nonebot-plugin-mahjong-utils#16]
我自己的QQ号上挂了这个机器人，电脑端挂机器人，手机自己用。因此，我使用的机器人框架设置是机器人会响应自己发出的信息，当我在群里发出"1234m"时，会导致回复的指令又触发了一遍，导致一致刷屏。
这里建议修改一下回复格式，比如在回复的文本最前面加一些符号绕开正则表达式，或是修改正则表达式匹配不要响应回复的格式。

**Comment by ssttkkl** [comment]
你可以fork一份自行修改一下指令格式实现

**Comment by ssttkkl** [comment]
或是使用图片格式发送结果https://github.com/bot-ssttkkl/nonebot-plugin-mahjong-utils?tab=readme-ov-file#mahjong_utils_send_image

**Comment by nqwu** [comment]
好的
